name = "xnxx-api"
main = "src/index.js"
compatibility_date = "2025-08-07"

[vars]
ENVIRONMENT = "production"

# Configuración para desarrollo local
[env.development]
name = "xnxx-api-dev"
vars = { ENVIRONMENT = "development" }
